services:
  api:
    build:
      context: .
      target: builder
    container_name: laik-tech-api
    ports:
      - '4000:4000'
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://postgres:postgres@db:5432/laik_tech
      PORT: 4000
      GRAPHQL_PLAYGROUND: 'true'
      GRAPHQL_DEBUG: 'true'
    volumes:
      - ./src:/app/src
    command: pnpm start:dev
    depends_on:
      db:
        condition: service_healthy
    networks:
      - laik-network

  db:
    image: postgres:16-alpine
    container_name: laik-tech-db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: laik_tech
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - laik-network

volumes:
  postgres_data:

networks:
  laik-network:
    driver: bridge
